version: "3.7"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/app
    ports:
      - 8080:8080
  redis:
    image: redis
